services:
  bastion:
    build:
      context: .
      dockerfile: container/Dockerfile
    volumes:
      - ./container:/app
    working_dir: /app
    tty: true
    environment:
      - TZ=Asia/Tokyo
      #- SLEEP_SECONDS=30
    restart: "no"
